# Generated by Django 4.2.2 on 2023-06-25 16:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_commandants"),
    ]

    operations = [
        migrations.RenameField(
            model_name="commandants",
            old_name="name",
            new_name="first_name",
        ),
        migrations.RenameField(
            model_name="students",
            old_name="name",
            new_name="first_name",
        ),
        migrations.AddField(
            model_name="students",
            name="room",
            field=models.CharField(default="", max_length=40, verbose_name="Комната"),
        ),
    ]
