# Generated by Django 4.2.2 on 2023-06-28 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0004_rename_name_commandants_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="commandants",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="auth.group",
            ),
        ),
    ]
