# Generated by Django 4.2.2 on 2023-06-28 15:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_mygroup"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mygroup",
            options={"verbose_name": "Роли", "verbose_name_plural": "Роли"},
        ),
    ]
