# Generated by Django 4.2.2 on 2023-06-28 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_alter_mygroup_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commandants",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.mygroup",
            ),
        ),
    ]
