# Generated by Django 4.2.2 on 2023-06-21 12:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Statement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=30, verbose_name="Название")),
                (
                    "payment",
                    models.BooleanField(default=False, verbose_name="Оплата общежития"),
                ),
                (
                    "status",
                    models.CharField(
                        default="Отправлено", max_length=30, verbose_name="Статус"
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=datetime.datetime(
                            2023, 6, 21, 12, 17, 4, 949017, tzinfo=datetime.timezone.utc
                        ),
                        verbose_name="Дата отправки",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="main/static/main/files",
                        verbose_name="Файл заявления",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявление",
                "verbose_name_plural": "Заявления",
            },
        ),
    ]
