# Generated by Django 4.2.2 on 2023-06-25 15:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0009_alter_statement_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dormitory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=30, verbose_name="Номер")),
                ("street", models.BooleanField(max_length=250, verbose_name="Адрес")),
            ],
            options={
                "verbose_name": "Общежитие",
                "verbose_name_plural": "Общежитие",
            },
        ),
        migrations.AlterField(
            model_name="statement",
            name="date",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 6, 25, 15, 55, 48, 311101, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Дата отправки",
            ),
        ),
    ]
