# Generated by Django 4.2.2 on 2023-06-25 15:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0010_dormitory_alter_statement_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dormitory",
            options={"verbose_name": "Общежитие", "verbose_name_plural": "Общежития"},
        ),
        migrations.AlterField(
            model_name="statement",
            name="date",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 6, 25, 15, 58, 42, 811969, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Дата отправки",
            ),
        ),
    ]
