# Generated by Django 4.2.2 on 2023-06-25 16:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0012_alter_statement_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dormitory",
            name="street",
            field=models.CharField(max_length=250, verbose_name="Адрес"),
        ),
        migrations.AlterField(
            model_name="statement",
            name="date",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 6, 25, 16, 15, 52, 238035, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Дата отправки",
            ),
        ),
    ]
