# Generated by Django 4.2.2 on 2023-06-28 12:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0014_statement_users_alter_statement_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="statement",
            old_name="users",
            new_name="student",
        ),
        migrations.AlterField(
            model_name="statement",
            name="date",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 6, 28, 12, 34, 14, 311017, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Дата отправки",
            ),
        ),
    ]
