# Generated by Django 4.2.5 on 2023-09-21 22:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_statement_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 9, 21, 22, 38, 39, 380178, tzinfo=datetime.timezone.utc), verbose_name='Дата отправки'),
        ),
        migrations.CreateModel(
            name='VisitHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.statement')),
            ],
            options={
                'verbose_name': 'История посещения',
                'verbose_name_plural': 'История посещений',
            },
        ),
    ]
