# Generated by Django 4.2.5 on 2023-09-21 22:42

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_statement_date_visithistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='visithistory',
            name='day_of_visit',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата посещения'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='statement',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 9, 21, 22, 42, 37, 605657, tzinfo=datetime.timezone.utc), verbose_name='Дата отправки'),
        ),
    ]
