# Generated by Django 4.2 on 2024-06-11 14:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0029_historicalstatement_draft_statement_draft_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalstatement",
            name="draft",
        ),
        migrations.RemoveField(
            model_name="statement",
            name="draft",
        ),
    ]
